### ISSUE TITLE
Non-critical cache error

### ISSUE THREAD

**Issue by pmaselkowski** [Maslosoft/Addendum#44]
**Quick Workaround - reload resource.**

Trace:

```
2016/10/06 21:13:03 [error] [php] array_diff_key(): Argument #2 is not an array (/var/www/websites/meno.pro/vendor/maslosoft/addendum/src/Cache/NsCache.php:159)
Stack trace:
#0 /var/www/websites/meno.pro/vendor/maslosoft/addendum/src/Cache/PhpCache.php(176): Maslosoft\Addendum\Cache\NsCache->valid()
#1 /var/www/websites/meno.pro/vendor/maslosoft/addendum/src/Builder/Builder.php(115): Maslosoft\Addendum\Cache\BuildOneCache->get()
#2 /var/www/websites/meno.pro/vendor/maslosoft/addendum/src/Builder/Builder.php(76): Maslosoft\Addendum\Builder\Builder->buildOne()
#3 /var/www/websites/meno.pro/vendor/maslosoft/addendum/src/Reflection/ReflectionAnnotatedClass.php(42): Maslosoft\Addendum\Builder\Builder->build()
#4 /var/www/websites/meno.pro/vendor/maslosoft/addendum/src/Addendum.php(238): Maslosoft\Addendum\Reflection\ReflectionAnnotatedClass->__construct()
#5 /var/www/websites/meno.pro/vendor/maslosoft/addendum/src/Collections/Meta.php(88): Maslosoft\Addendum\Addendum->annotate()
#6 /var/www/websites/meno.pro/vendor/maslosoft/ilmatar-components/src/Meta/IlmatarMeta.php(34): Maslosoft\Ilmatar\Components\Meta\IlmatarMeta->__construct()
#7 /var/www/websites/meno.pro/vendor/maslosoft/addendum/src/Collections/Meta.php(257): Maslosoft\Ilmatar\Components\Meta\IlmatarMeta->__construct()
#8 /var/www/websites/meno.pro/vendor/maslosoft/ilmatar-components/src/Meta/IlmatarMeta.php(53): create()
#9 /var/www/websites/meno.pro/vendor/maslosoft/ilmatar-components/src/MongoDocument.php(191): create()
#10 /var/www/websites/meno.pro/vendor/maslosoft/hi5edit/src/Blocks/Base/ContentBlock.php(72): Maslosoft\Hi5Edit\Blocks\Carousel\Carousel->__construct()
#11 /var/www/websites/meno.pro/vendor/maslosoft/hi5edit/src/Blocks/Carousel/Carousel.php(82): Maslosoft\Hi5Edit\Blocks\Carousel\Carousel->__construct()
#12 /var/www/websites/meno.pro/vendor/maslosoft/signals/src/Factories/SlotFactory.php(54): Maslosoft\Hi5Edit\Blocks\Carousel\Carousel->__construct()
#13 /var/www/websites/meno.pro/vendor/maslosoft/signals/src/Signal.php(271): create()
#14 /var/www/websites/meno.pro/vendor/maslosoft/hi5edit/src/Components/WidgetManager.php(38): Maslosoft\Signals\Signal->emit()
#15 /var/www/websites/meno.pro/vendor/maslosoft/hi5edit/src/Editor.php(112): Maslosoft\Hi5Edit\Components\WidgetManager->__construct()
#16 /var/www/websites/meno.pro/vendor/maslosoft/embedi/src/EmbeDi.php(329): Maslosoft\Hi5Edit\Editor->__construct()
#17 /var/www/websites/meno.pro/vendor/maslosoft/ilmatar-widgets/src/MsWidget.php(321): Maslosoft\EmbeDi\EmbeDi->apply()
```

**Comment by pmaselkowski** [comment]
4a68c69
